all:
  children:
    switches:
      children:
        intermediate:
          hosts:  
            viosswitch1:
              ansible_host: "172.16.0.11"
            viosswitch2:
              ansible_host: "172.16.0.12"
        access:
          hosts:
            viosswitch3:
              ansible_host: "172.16.0.13"
            viosswitch4: 
              ansible_host: "172.16.0.14"  
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_becomee_method: enable
    ansible_user: "cisco"
    ansible_password: "cisco"